[package]
name = "f-miniscript"
version = "0.1.0"
edition = "2024"

[dependencies]
bitcoin = { version = "0.30", default-features = false, features = ["no-std"] }
heapless = "0.8.0"

[lib]
crate-type = ["lib"]




